apiVersion: apps/v1
kind: Deployment
metadata:
  name: iweblens-app
  labels:
    app: iweblens
spec:
  selector:
    matchLabels:
      app: iweblens
  replicas: 1
  template:
    metadata:
      labels:
        app: iweblens
    spec:
      containers:
      - name: iweblens-app
        image: iweblens
        ports:
          - containerPort: 80
        imagePullPolicy: Never
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.5"