apiVersion: v1
kind: Service
metadata:
  name: iweblens-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  selector:
    app: iweblens
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: iweblens-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: iweblens-svc
          servicePort: 80
---