apiVersion: v1
  kind: Service
metadata:
  name: iweblens-svc 
  labels:
    app: iweb-lens 
spec:
  type: NodePort 
  ports:
  - port: 80
    nodePort: 5000
    protocol: TCP
  selector:
    app: iweb-lens 